### Numpy

In [ ]:
#Initialize an array and print its type
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
print('A is of type:', type(a))
print(a)

A is of type: <class 'numpy.ndarray'>
[1 2 3 4 5 6]


In [ ]:
#multidimensional array
import numpy as np
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14,
15, 16]])

print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
a[0,2]

3

In [ ]:
#Different mathematical operations over a matrix
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
b1=10*a
b2=np.multiply(10,a)
print(a)
print(b1)
print(b2)

c=np.log(a)
d=np.sqrt(a)
e=a**2  #This squares the value.
print(c)
print(d)
print(e)

[1 2 3 4 5 6]
[10 20 30 40 50 60]
[10 20 30 40 50 60]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[ 1  4  9 16 25 36]


In [ ]:
print(np.square(a))

[ 1  4  9 16 25 36]


In [ ]:
#Generate random distributions
a = np.random.uniform(50, 150, 10)  #Between 50-150, generate 10 variables from uniform
b = np.random.standard_normal(10)   #With mean 0 and standard deviation 1 
print(a)
print(b)

In [ ]:
np.random.random((2,2))

array([[0.92905868, 0.98683861],
       [0.04030097, 0.39030082]])

#### Class Exercises

####Q1. Given an array 

In [ ]:

import numpy as np

arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

print(arr)
print(arr[:2, ::2])

####Q2. Print the elements at a specific index

In [ ]:
import numpy as np

arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

print(arr[[1, 1, 0, 3], [3, 2, 1, 0]])

[0. 6. 2. 3.]


####Q3. Add any two given arrays

In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4]]) 
b = np.array([[4, 3], [2, 1]])

print(a+b)

####Q4. a = np.array([4.0 9.0])

In [ ]:
print(type(a))

<class 'numpy.ndarray'>


####Q5. Use the previous array and find the square root 

In [ ]:
x=np.array([4.0, 9.0])
print(np.sqrt(x))

[2. 3.]


####Q6. Get unique values in a list using numpy

In [ ]:
import numpy as np 
  
# function to get unique values 
def uniquevals(list1): 
    x = np.array(list1) 
    print(np.unique(x)) 

list1 = [10, 20, 10, 30, 40, 40] 
uniquevals(list1)

#Easy way --> print(np.unique(np.array(list1)))

[10 20 30 40]


####Q7. Multiply all the numbers in a list using numpy

In [ ]:
import numpy as np
list1 = [1, 2, 3, 4]  
result1 = np.prod(list1)

print(result1)


24


####Q8. Create a random numpy array of 20 rows and 2 columns

In [ ]:
a=np.random((20,2))
print(a)

###Pandas

#### Pandas Overview 

- Most popular python library for data analysis
- Highly optimized performance
- Using: 1) Series; 2) DataFrames

#### Series 
- One dimensional array to store any data type


In [ ]:
#format of creating a series
import pandas as pd

data=[1, 2, 3, 4]
#index=range(len(data))
index=['a', 'b', 'c', 'd']
a = pd.Series(data, index=index)
print(a)

#Data can be Scalar value – integer, string; Dictionary – <key, value> pair
#or an Ndarray

#index by default is from 0, 1, 2, ... (n-1)
#where n is the length of the data

a    1
b    2
c    3
d    4
dtype: int64


In [ ]:
print(a['c'])

3


In [ ]:
#As mentioned earlier, data can be a list of lists as well
import pandas as pd

index=[[1,2], [1,3], [1,4]]
#1,1,1, <data value>
#2,3,4, <data value>
data=range(len(index[0]))
a = pd.Series(data, index=index)
print(a)

1  1  1    0
2  3  4    1
dtype: int64


In [ ]:
index = [['a','b','c','e'],['a','d','c','d'],['f','b','k','d'],['s','b','c','d']]
data = [1, 2, 3, 4]
a= pd.Series(data, index = index)
print(a)

a  a  f  s    1
b  d  b  b    2
c  c  k  c    3
e  d  d  d    4
dtype: int64


In [ ]:
#You can use the data as a dictionary
#keys will become index and values will be column values
#Series -- 1-D array to store any data type -- here dictionary
import pandas as pd

data={1:'a', 2:'b', 3:'c', 4:'d', 5:'e', 6:'f'}
a = pd.Series(data)
print(a)

1    a
2    b
3    c
4    d
5    e
6    f
dtype: object


##### In the previous question, what happens if I provide the dictionary 
##### this way: data={1:'a', 2:'b', 3:'c', 4:'d', 4:'e', 5:'f'}

In [ ]:
import pandas as pd

data={1:'a', 2:'b', 3:'c', 4:'d', 4:'e', 5:'f'}
a = pd.Series(data)
print(a)

1    a
2    b
3    c
4    e
5    f
dtype: object


#### Dataframes

DataFrame is a two-dimensional data structure that consists of rows
and columns

In [ ]:
import pandas as pd
df = pd.DataFrame(data)

#data can be One or more dictionaries; one or more series; 2D-numpy Ndarray

##### Data can be one or more dictionaries

In [ ]:

import numpy as np
diction1 ={'a':1, 'b':2, 'c':3, 'd':4}
diction2 ={'a':5, 'b':6, 'c':7, 'd':8}
data = {'first':diction1, 'second':diction2}
df = pd.DataFrame(data)
print(df)

   first  second
a      1       5
b      2       6
c      3       7
d      4       8


In [ ]:
low=df.index[df['second'] < 7].tolist()
high=df.index[df['second'] >= 7].tolist()
df.loc[low,'second']='low'
df.loc[high,'second']='high'


In [ ]:
print(df)

   first second
a      1    low
b      2    low
c      3   high
d      4   high


##### Data can be one or more series

In [ ]:
s1 = pd.Series([1, 3, 5, 7, 9, 11, 13])
s2 = pd.Series([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8])
s3 = pd.Series(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'])

data ={'first':s1, 'second':s2, 'third':s3}
df = pd.DataFrame(data)
print(df)

   first  second third
0    1.0     1.1     a
1    3.0     2.2     b
2    5.0     3.3     c
3    7.0     4.4     d
4    9.0     5.5     e
5   11.0     6.6     f
6   13.0     7.7     g
7    NaN     8.8     h
8    NaN     NaN     i


In [ ]:
l7=[2,4,6,8]
l71=list(l7)
l71.append(l7[0])
l72=list(l71)
l72.append(sum(l71)/len(l71))

data = {'first':pd.Series(l7), 'second':pd.Series(l71), 'third':pd.Series(l72)}
df = pd.DataFrame(data)
print(df)
print(list(df['second'])[:5]==[2.0,4.0,6.0,8.0,2.0])

   first  second  third
0    2.0     2.0    2.0
1    4.0     4.0    4.0
2    6.0     6.0    6.0
3    8.0     8.0    8.0
4    NaN     2.0    2.0
5    NaN     NaN    4.4
True


##### Data can be a 2D numpy array

In [ ]:
import numpy as np
import pandas as pd
data = np.array([[1, 2], [3, 4]])
df = pd.DataFrame(data)
print(df)

   0  1
0  1  2
1  3  4


In [ ]:
import numpy as np
import pandas as pd
data = np.array([[1, 2], [3, 4]])
df = pd.DataFrame({'col1':data[:,0], 'col2':data[:,1]})
print(df)

##### Now create a small dataframe with 2 columns

In [ ]:
import pandas as pd
data={'Name': ['John', 'William', 'Ian', 'Noah'], 'Age':[12, 15, 13, 12]}
df = pd.DataFrame(data)
print(df)

      Name  Age
0     John   12
1  William   15
2      Ian   13
3     Noah   12


#### Read a .csv file and load it in a dataframe




In [ ]:
#Upload a file to the notebook 
from google.colab import files
uploaded = files.upload()

Saving nba.csv to nba (1).csv


In [ ]:
# Read the basketball dataset
import pandas as pd
nbadf = pd.read_csv("nba.csv", index_col="Name")
first=nbadf['Age']
print(first)

Name
Avery Bradley    25.0
Jae Crowder      25.0
John Holland     27.0
R.J. Hunter      22.0
Jonas Jerebko    29.0
                 ... 
Shelvin Mack     26.0
Raul Neto        24.0
Tibor Pleiss     26.0
Jeff Withey      26.0
NaN               NaN
Name: Age, Length: 458, dtype: float64


In [ ]:
#Now print the info of the dataframe
nbadf.info()

<class 'pandas.core.frame.DataFrame'>
Index: 458 entries, Avery Bradley to nan
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Team      457 non-null    object 
 1   Number    457 non-null    float64
 2   Position  457 non-null    object 
 3   Age       457 non-null    float64
 4   Height    457 non-null    object 
 5   Weight    457 non-null    float64
 6   College   373 non-null    object 
 7   Salary    446 non-null    float64
dtypes: float64(4), object(4)
memory usage: 32.2+ KB


#### I want to access basic statistics about this dataset

In [ ]:
import numpy as np
nbadf.describe(include='all')

Team      Number  ...   College        Salary
count                    457  457.000000  ...       373  4.460000e+02
unique                    30         NaN  ...       118           NaN
top     New Orleans Pelicans         NaN  ...  Kentucky           NaN
freq                      19         NaN  ...        22           NaN
mean                     NaN   17.678337  ...       NaN  4.842684e+06
std                      NaN   15.966090  ...       NaN  5.229238e+06
min                      NaN    0.000000  ...       NaN  3.088800e+04
25%                      NaN    5.000000  ...       NaN  1.044792e+06
50%                      NaN   13.000000  ...       NaN  2.839073e+06
75%                      NaN   25.000000  ...       NaN  6.500000e+06
max                      NaN   99.000000  ...       NaN  2.500000e+07

[11 rows x 8 columns]

In [ ]:
#describe function doesnt provide summary stats on np.objects
import numpy as np
nbadf.describe(include=np.object)

In [ ]:
#I want to see all the columns described
import numpy as np
nbadf.describe(include='all')

#### Accessing the elements in a dataframe


In [ ]:
#Create a dataframe and print only two columns -- name and address
import pandas as pd

data={'Name':['John', 'Jim', 'Ashley', 'Aimee', 'Jeff'],'Age':[24, 25, 22, 23, 27], 'Address': ['New York', 'Arizona','Minnesota', 'California', 'New York'], 'Qualification': ['MS', 'BS', 'BS', 'MS', 'PhD']}
df = pd.DataFrame(data)
print(df)
print(list(df['Name'])==['John', 'Jim', 'Ashley', 'Aimee', 'Jeff'])
print(df['Address'])

     Name  Age     Address Qualification
0    John   24    New York            MS
1     Jim   25     Arizona            BS
2  Ashley   22   Minnesota            BS
3   Aimee   23  California            MS
4    Jeff   27    New York           PhD
True
0      New York
1       Arizona
2     Minnesota
3    California
4      New York
Name: Address, dtype: object


In [ ]:
# for the nba dataset how do we access specific rows and columns
#access rows using the index 
first = nbadf.loc["Avery Bradley"]
second = nbadf.loc["R.J. Hunter"]
print(first)
print(second)

Team        Boston Celtics
Number                   0
Position                PG
Age                     25
Height                 6-2
Weight                 180
College              Texas
Salary         7.73034e+06
Name: Avery Bradley, dtype: object
Team        Boston Celtics
Number                  28
Position                SG
Age                     22
Height                 6-5
Weight                 185
College      Georgia State
Salary         1.14864e+06
Name: R.J. Hunter, dtype: object


In [ ]:
#How about accessing rows with their ids
arow = nbadf.iloc[23]
print(arow)

Team        Brooklyn Nets
Number                 11
Position                C
Age                    28
Height                7-0
Weight                275
College          Stanford
Salary         1.9689e+07
Name: Brook Lopez, dtype: object


In [ ]:
#Count the number of rows
nbadf['Team'].count()

457

In [ ]:
#I want to count how many unique values occur in a column, here it is 
#"team column"
nbadf['Team'].value_counts()

New Orleans Pelicans      19
Memphis Grizzlies         18
New York Knicks           16
Milwaukee Bucks           16
Atlanta Hawks             15
Brooklyn Nets             15
Dallas Mavericks          15
Washington Wizards        15
Golden State Warriors     15
Philadelphia 76ers        15
Los Angeles Lakers        15
Sacramento Kings          15
Los Angeles Clippers      15
Chicago Bulls             15
Phoenix Suns              15
Toronto Raptors           15
Charlotte Hornets         15
Denver Nuggets            15
Cleveland Cavaliers       15
Portland Trail Blazers    15
Utah Jazz                 15
Houston Rockets           15
Boston Celtics            15
Oklahoma City Thunder     15
San Antonio Spurs         15
Miami Heat                15
Indiana Pacers            15
Detroit Pistons           15
Minnesota Timberwolves    14
Orlando Magic             14
Name: Team, dtype: int64

In [ ]:
#What is the maximum age of players
nbadf['Age'].describe()

count    457.000000
mean      26.938731
std        4.404016
min       19.000000
25%       24.000000
50%       26.000000
75%       30.000000
max       40.000000
Name: Age, dtype: float64

In [ ]:
#what is the maximum age of players in Los Angeles Lakers
#nbadf.loc[nbadf['Team']=='Los Angeles Lakers']['Age']

#What if I just want to describe this list of all players ages
nbadf.loc[nbadf['Team']=='Los Angeles Lakers']['Age'].describe()

count    15.000000
mean     27.533333
std       5.289702
min      20.000000
25%      23.500000
50%      27.000000
75%      31.000000
max      37.000000
Name: Age, dtype: float64

##### Can I find the age of all players in another way -- yes you can

In [ ]:
nbadf['Age'][nbadf['Team']=='Los Angeles Lakers']

Name
Brandon Bass         31.0
Tarik Black          24.0
Anthony Brown        23.0
Kobe Bryant          37.0
Jordan Clarkson      24.0
Roy Hibbert          29.0
Marcelo Huertas      33.0
Ryan Kelly           25.0
Larry Nance Jr.      23.0
Julius Randle        21.0
D'Angelo Russell     20.0
Robert Sacre         27.0
Louis Williams       29.0
Metta World Peace    36.0
Nick Young           31.0
Name: Age, dtype: float64

In [ ]:
#What are the teams that have players from Stanford
nbadf['Team'][nbadf['College']=='Stanford']

Name
Brook Lopez              Brooklyn Nets
Robin Lopez            New York Knicks
Anthony Brown       Los Angeles Lakers
Dwight Powell         Dallas Mavericks
Josh Huestis     Oklahoma City Thunder
Name: Team, dtype: object

#### Grouping 


In [ ]:
#Group the rows based on a certain common attribute 
#What are the teams that are there in our dataset

nbadf.groupby(['Team']).groups.keys()

dict_keys(['Atlanta Hawks', 'Boston Celtics', 'Brooklyn Nets', 'Charlotte Hornets', 'Chicago Bulls', 'Cleveland Cavaliers', 'Dallas Mavericks', 'Denver Nuggets', 'Detroit Pistons', 'Golden State Warriors', 'Houston Rockets', 'Indiana Pacers', 'Los Angeles Clippers', 'Los Angeles Lakers', 'Memphis Grizzlies', 'Miami Heat', 'Milwaukee Bucks', 'Minnesota Timberwolves', 'New Orleans Pelicans', 'New York Knicks', 'Oklahoma City Thunder', 'Orlando Magic', 'Philadelphia 76ers', 'Phoenix Suns', 'Portland Trail Blazers', 'Sacramento Kings', 'San Antonio Spurs', 'Toronto Raptors', 'Utah Jazz', 'Washington Wizards'])

In [ ]:
nbadf.groupby(['Team']).groups

{'Atlanta Hawks': ['Kent Bazemore', 'Tim Hardaway Jr.', 'Kirk Hinrich', 'Al Horford', 'Kris Humphries', 'Kyle Korver', 'Paul Millsap', 'Mike Muscala', 'Lamar Patterson', 'Dennis Schroder', 'Mike Scott', 'Thabo Sefolosha', 'Tiago Splitter', 'Walter Tavares', 'Jeff Teague'], 'Boston Celtics': ['Avery Bradley', 'Jae Crowder', 'John Holland', 'R.J. Hunter', 'Jonas Jerebko', 'Amir Johnson', 'Jordan Mickey', 'Kelly Olynyk', 'Terry Rozier', 'Marcus Smart', 'Jared Sullinger', 'Isaiah Thomas', 'Evan Turner', 'James Young', 'Tyler Zeller'], 'Brooklyn Nets': ['Bojan Bogdanovic', 'Markel Brown', 'Wayne Ellington', 'Rondae Hollis-Jefferson', 'Jarrett Jack', 'Sergey Karasev', 'Sean Kilpatrick', 'Shane Larkin', 'Brook Lopez', 'Chris McCullough', 'Willie Reed', 'Thomas Robinson', 'Henry Sims', 'Donald Sloan', 'Thaddeus Young'], 'Charlotte Hornets': ['Nicolas Batum', 'Troy Daniels', 'Jorge Gutierrez', 'Tyler Hansbrough', 'Aaron Harrison', 'Spencer Hawes', 'Al Jefferson', 'Frank Kaminsky III', 'Michael 

##### Can we find the players age for each team instead of just LA Lakers



In [ ]:
#Grouping players from each team in our dataset 
nbadf.groupby('Team')['Age'].describe()

count       mean       std  ...   50%    75%   max
Team                                                ...                   
Boston Celtics           15.0  24.733333  2.840188  ...  25.0  27.00  29.0
Brooklyn Nets            15.0  25.600000  3.018988  ...  26.0  27.50  32.0
New York Knicks          16.0  27.000000  4.179314  ...  26.0  30.50  34.0
Philadelphia 76ers       15.0  24.600000  4.563833  ...  24.0  25.00  37.0
Toronto Raptors          15.0  26.133333  3.961722  ...  25.0  29.00  36.0
Golden State Warriors    15.0  27.666667  3.848314  ...  28.0  30.50  33.0
Los Angeles Clippers     15.0  29.466667  4.897035  ...  29.0  31.00  39.0
Los Angeles Lakers       15.0  27.533333  5.289702  ...  27.0  31.00  37.0
Phoenix Suns             15.0  25.866667  4.240395  ...  25.0  29.00  33.0
Sacramento Kings         15.0  26.800000  3.529468  ...  27.0  28.50  36.0
Chicago Bulls            15.0  27.400000  4.188419  ...  27.0  30.50  35.0
Cleveland Cavaliers      15.0  29.533333  4.120795  ...  30.0  33.00  35.0
Detroit Pistons          15.0  26.200000  4.443294  ...  25.0  28.50  36.0
Indiana Pacers           15.0  26.400000  3.157757  ...  27.0  29.00  30.0
Milwaukee Bucks          16.0  24.562500  3.520772  ...  24.5  27.00  32.0
Dallas Mavericks         15.0  29.733333  3.712271  ...  31.0  31.50  37.0
Houston Rockets          15.0  26.866667  4.323799  ...  27.0  30.00  38.0
Memphis Grizzlies        18.0  28.388889  5.585052  ...  28.0  33.25  39.0
New Orleans Pelicans     19.0  26.894737  2.233451  ...  27.0  28.50  31.0
San Antonio Spurs        15.0  31.600000  5.766901  ...  33.0  35.50  40.0
Atlanta Hawks            15.0  28.200000  4.229151  ...  27.0  31.00  35.0
Charlotte Hornets        15.0  26.133333  3.159265  ...  27.0  28.50  31.0
Miami Heat               15.0  28.933333  4.861902  ...  30.0  32.50  36.0
Orlando Magic            14.0  25.071429  3.429830  ...  24.5  26.00  32.0
Washington Wizards       15.0  27.866667  4.389381  ...  29.0  31.00  34.0
Denver Nuggets           15.0  25.733333  4.742915  ...  25.0  28.00  36.0
Minnesota Timberwolves   14.0  26.357143  5.930458  ...  25.0  28.75  40.0
Oklahoma City Thunder    15.0  27.066667  4.832430  ...  26.0  29.00  38.0
Portland Trail Blazers   15.0  25.066667  3.634491  ...  24.0  26.50  34.0
Utah Jazz                15.0  24.466667  2.445599  ...  24.0  26.00  28.0

[30 rows x 8 columns]

##### Group by players based on their college and find the summary stats of the salary they earn

In [ ]:
nbadf.groupby("College", sort=False)['Salary'].describe()

#nbadf.groupby("College", sort=False)['Salary'].max()

#nbadf.groupby("College", sort=False)['Salary'].count()


count          mean  ...          75%         max
College                                 ...                         
Texas                9.0  8.968001e+06  ...  14260870.00  20158622.0
Marquette            5.0  1.198129e+07  ...  16407500.00  20000000.0
Boston University    0.0           NaN  ...          NaN         NaN
Georgia State        1.0  1.148640e+06  ...   1148640.00   1148640.0
LSU                  6.0  1.258010e+06  ...   1215870.00   3000000.0
...                  ...           ...  ...          ...         ...
Weber State          1.0  4.236287e+06  ...   4236287.00   4236287.0
Lehigh               1.0  2.525160e+06  ...   2525160.00   2525160.0
Westchester CC       1.0  5.250930e+05  ...    525093.00    525093.0
Dayton               2.0  1.918144e+06  ...   2386542.00   2854940.0
Butler               2.0  8.921452e+06  ...  12165510.75  15409570.0

[118 rows x 8 columns]

#####How about now access one row from this groupby lets say stanford

In [ ]:
stanford = nbadf.groupby('College', sort=False)
stanford.get_group('Stanford')

Team  Number  ...   College      Salary
Name                                          ...                      
Brook Lopez            Brooklyn Nets    11.0  ...  Stanford  19689000.0
Robin Lopez          New York Knicks     8.0  ...  Stanford  12650000.0
Anthony Brown     Los Angeles Lakers     3.0  ...  Stanford    700000.0
Dwight Powell       Dallas Mavericks     7.0  ...  Stanford    845059.0
Josh Huestis   Oklahoma City Thunder    34.0  ...  Stanford   1140240.0

[5 rows x 8 columns]

##### You can group values using multiple columns

##### lets group the teams and then their colleges.. 

In [ ]:
nbadf.groupby(["Team", "College"])['Salary'].describe()


count  ...         max
Team               College                      ...            
Atlanta Hawks      Bucknell                1.0  ...    947276.0
                   Creighton               1.0  ...   5746479.0
                   Florida                 1.0  ...  12000000.0
                   Kansas                  1.0  ...   2854940.0
                   Louisiana Tech          1.0  ...  18671659.0
...                                        ...  ...         ...
Washington Wizards LSU                     2.0  ...   1100602.0
                   Michigan State          1.0  ...   4000000.0
                   Nevada                  1.0  ...   2170465.0
                   North Carolina State    1.0  ...    273038.0
                   Virginia Tech           1.0  ...    561716.0

[336 rows x 8 columns]

In [ ]:
#I want to do the other way round -- 
#first group the values using their college and then team

nbadf.groupby(["College", "Team"])['Salary'].describe()


count       mean  ...         75%        max
College   Team                                    ...                       
Alabama   Cleveland Cavaliers     1.0  2100000.0  ...  2100000.00  2100000.0
          Memphis Grizzlies       1.0   845059.0  ...   845059.00   845059.0
          New Orleans Pelicans    1.0  1320000.0  ...  1320000.00  1320000.0
Arizona   Brooklyn Nets           1.0  1335480.0  ...  1335480.00  1335480.0
          Cleveland Cavaliers     2.0  4570152.5  ...  6381590.75  8193029.0
...                               ...        ...  ...         ...        ...
Wisconsin Houston Rockets         1.0  1646400.0  ...  1646400.00  1646400.0
          Phoenix Suns            1.0  1035000.0  ...  1035000.00  1035000.0
          Sacramento Kings        1.0   525093.0  ...   525093.00   525093.0
Wyoming   Los Angeles Lakers      1.0  1155600.0  ...  1155600.00  1155600.0
Xavier    San Antonio Spurs       1.0  1499187.0  ...  1499187.00  1499187.0

[336 rows x 8 columns]

#### Filling missing values

In [ ]:
# Find all the missing values in the dataframe
nbadf.isnull()

Team  Number  Position    Age  Height  Weight  College  Salary
Name                                                                          
Avery Bradley  False   False     False  False   False   False    False   False
Jae Crowder    False   False     False  False   False   False    False   False
John Holland   False   False     False  False   False   False    False    True
R.J. Hunter    False   False     False  False   False   False    False   False
Jonas Jerebko  False   False     False  False   False   False     True   False
...              ...     ...       ...    ...     ...     ...      ...     ...
Shelvin Mack   False   False     False  False   False   False    False   False
Raul Neto      False   False     False  False   False   False     True   False
Tibor Pleiss   False   False     False  False   False   False     True   False
Jeff Withey    False   False     False  False   False   False    False   False
NaN             True    True      True   True    True    True     True    True

[458 rows x 8 columns]

In [ ]:
#Count them
nbadf.isnull().sum().sum()

103

In [ ]:
#In a specific column? 
print(pd.isnull(nbadf["Team"]))

Name
Avery Bradley    False
Jae Crowder      False
John Holland     False
R.J. Hunter      False
Jonas Jerebko    False
                 ...  
Shelvin Mack     False
Raul Neto        False
Tibor Pleiss     False
Jeff Withey      False
NaN               True
Name: Team, Length: 458, dtype: bool


####How to fill up missing values? 


In [ ]:
dummy = {'First':[100, 90, np.nan, 95], 
        'Second': [30, 45, 56, np.nan], 
        'Third':[np.nan, 40, 80, 98]} 
  
ddf = pd.DataFrame(dummy) 

print(ddf)
# using notnull() function  
ddf.notnull() 

   First  Second  Third
0  100.0    30.0    NaN
1   90.0    45.0   40.0
2    NaN    56.0   80.0
3   95.0     NaN   98.0


First  Second  Third
0   True    True  False
1   True    True   True
2  False    True   True
3   True   False   True

In [ ]:
#Replace them with a specific value
ddf.fillna(0)


In [ ]:
#Replace with forward fill ffill()
ddf.ffill()

First  Second  Third
0  100.0    30.0    NaN
1   90.0    45.0   40.0
2   90.0    56.0   80.0
3   95.0    56.0   98.0

In [ ]:
#replace with backward fill()
ddf.bfill()

First  Second  Third
0  100.0    30.0   40.0
1   90.0    45.0   40.0
2   95.0    56.0   80.0
3   95.0     NaN   98.0

In [ ]:
#If you want to drop the rows with atleast one missing value
ddf.dropna()


First  Second  Third
1   90.0    45.0   40.0

In [ ]:
#Drop a row with all the missing values
ddf.dropna(how='all')

First  Second  Third
0  100.0    30.0    NaN
1   90.0    45.0   40.0
2    NaN    56.0   80.0
3   95.0     NaN   98.0

In [ ]:
#What about columns
#drop a column which has at least 1 missing value

ddf.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

#### Class Exercises

#### Q1. Load the 'titanic.csv' file and load it into a dataframe 

In [ ]:
from google.colab import files
uploaded = files.upload()



Saving titanic.csv to titanic (1).csv


In [ ]:
import pandas as pd
tdf = pd.read_csv("titanic.csv")
print(tdf)

     survived  pclass  gender   age  ...  deck  embark_town  alive  alone
0           0       3    male  22.0  ...   NaN  Southampton     no  False
1           1       1  female  38.0  ...     C    Cherbourg    yes  False
2           1       3  female  26.0  ...   NaN  Southampton    yes   True
3           1       1  female  35.0  ...     C  Southampton    yes  False
4           0       3    male  35.0  ...   NaN  Southampton     no   True
..        ...     ...     ...   ...  ...   ...          ...    ...    ...
886         0       2    male  27.0  ...   NaN  Southampton     no   True
887         1       1  female  19.0  ...     B  Southampton    yes   True
888         0       3  female   NaN  ...   NaN  Southampton     no  False
889         1       1    male  26.0  ...     C    Cherbourg    yes   True
890         0       3    male  32.0  ...   NaN   Queenstown     no   True

[891 rows x 15 columns]


####Q2. Find the summary statistics and then print the names of columns

In [ ]:
tdf.describe()
#tdf.describe(include='all')
print(tdf.columns)



Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')
891
15


####Q3. Find the number of rows and columns in this dataset


In [ ]:
#Approach-1
rows=len(tdf)
cols=len(tdf.columns)
print(rows)
print(cols)

'''#Approach-2

rows = len(tdf.axes[0]) 
cols = len(tdf.axes[1]) 
print(rows)
print(cols)'''


#### Q4. Find the number of rows that have atleast one missing value



In [ ]:
#Total number of missing values
print(tdf.isnull().sum().sum()) #For the entire dataframe

#Check how the data looks like
print(tdf.isnull())

#Across columns
print(tdf.isnull().sum())

#Across rows 
#for i in range(len(tdf)):
#  print(tdf.iloc[i].isnull().sum())

#Now total number of rows with atleast 1 null value
nullrows=0
for i in range(len(tdf)):
  if (tdf.iloc[i].isnull().sum())>0:
    nullrows+=1

print(nullrows)

####Q5. Group by those who survived and class. Then find their maximum age in that group. 

In [ ]:
#tdf.groupby(['survived', 'class'])['age'].describe()
tdf.groupby(['survived', 'class'])['age'].max()

survived  class 
0         First     71.0
          Second    70.0
          Third     74.0
1         First     80.0
          Second    62.0
          Third     63.0
Name: age, dtype: float64

In [ ]:
#How many 'woman' and 'child' survived

print((tdf.loc[tdf['survived']==1]['who']=='woman').sum())
print((tdf.loc[tdf['survived']==1]['who']=='child').sum())
#tdf.groupby(['survived', 'who']).describe()

205
49


In [ ]:
tdf.isnull().sum().sum()

869

In [ ]:
tdf['age'].sum()==21205.17

True

In [ ]:
gpd=tdf.groupby(['embark_town', 'gender'])
#print(gpd.describe())
print(gpd.get_group(('Southampton','female')).sum())

survived                                                     140
pclass                                                       446
gender         femalefemalefemalefemalefemalefemalefemalefema...
age                                                       5165.5
sibsp                                                        170
parch                                                        160
fare                                                     7864.41
embarked       SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...
class          ThirdFirstThirdThirdFirstThirdSecondThirdThird...
who            womanwomanwomanchildwomanchildwomanwomanchildw...
adult_male                                                     0
embark_town    SouthamptonSouthamptonSouthamptonSouthamptonSo...
alive          yesyesyesyesyesnoyesnonoyesnonononoyesyesyesye...
alone                                                         72
dtype: object
